version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TMDB_V3_API_KEY: ${TMDB_V3_API_KEY}  # Pass the API key as a build argument
    environment:
      - VITE_APP_TMDB_V3_API_KEY=${TMDB_V3_API_KEY}
      - VITE_APP_API_ENDPOINT_URL="https://api.themoviedb.org/3"
    ports:
      - "80:80"  # Map port 80 on the host to port 80 in the container

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html
    restart: always
